name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify base href in index.html
        run: |
          sed -i 's|<base href="/">|<base href="/shieldbot-web/">|g' index.html

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Copy build to root
        run: |
          cp -r build/web/* ./

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: ./
          token: ${{ secrets.GITHUB_TOKEN }}
